name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # PHP & Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite
          coverage: none

      # Env files
      - name: Prepare environment
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=:memory:" >> .env.testing

      # Dependencies
      - name: Install Composer deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      # Cache & perms
      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # Run tests
      - name: Run PHPUnit / Pest
        run: php artisan test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS with Docker
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/laravel-app

            # Update repository
            if [ ! -d .git ]; then
              git clone ${{ github.server_url }}/${{ github.repository }} .
            else
              git fetch --all
              git reset --hard origin/$(echo ${{ github.ref }} | sed 's|refs/heads/||')
            fi

            # Prepare environment file if not exists
            if [ ! -f .env ]; then
              cp .env.example .env
              sed -i 's/DB_HOST=.*/DB_HOST=mysql/' .env
              sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel/' .env
              sed -i 's/DB_USERNAME=.*/DB_USERNAME=laravel_user/' .env
              sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=laravel_password/' .env
            fi

            # Ensure proper permissions
            chmod -R 775 storage bootstrap/cache

            # Docker operations
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d

            # Run migrations and optimizations inside container
            docker-compose exec -T app composer install --no-interaction --prefer-dist --no-dev
            docker-compose exec -T app php artisan key:generate --force
            docker-compose exec -T app php artisan migrate --force
            docker-compose exec -T app php artisan config:cache
            docker-compose exec -T app php artisan route:cache
            docker-compose exec -T app php artisan view:cache

            # If using queue
            docker-compose exec -T app php artisan queue:restart
          EOF
