name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
# ---------- TEST ----------
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite
          coverage: none

      - name: Prepare environment files
        run: |
          cp .env.example .env
          cp .env.example .env.testing
          sed -i "s|^APP_KEY=.*|APP_KEY=base64:$(openssl rand -base64 32)|" .env
          sed -i "s|^APP_KEY=.*|APP_KEY=base64:$(openssl rand -base64 32)|" .env.testing
          sed -i "s|^APP_ENV=.*|APP_ENV=testing|" .env.testing
          sed -i "s|^DB_CONNECTION=.*|DB_CONNECTION=sqlite|" .env.testing
          sed -i "s|^DB_DATABASE=.*|DB_DATABASE=:memory:|" .env.testing

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run test migrations
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan migrate --force

# ---------- DEPLOY ----------
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            set -e
            PROJECT_DIR=/var/www/laravel-app
            cd \$PROJECT_DIR

            # --- Update repository ---
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}

            # --- Ensure .env & APP_KEY (host file) ---
            [ -f .env ] || cp .env.example .env
            if ! grep -q '^APP_KEY=base64:' .env; then
              docker run --rm -v \$(pwd):/app -w /app laravelsail/php82-composer:latest \
                php artisan key:generate --no-interaction
            fi

            # --- (Re)build & start containers (upgrade PHP 8.2 jika perlu) ---
            PHP_VER=\$(docker compose exec -T app php -r "echo PHP_VERSION;" || echo "")
            if [ "\$PHP_VER" != "\${PHP_VER/8.1/}" ]; then
              echo "Rebuilding container with PHP 8.2..."
              docker compose down || true
              docker compose build --no-cache --build-arg PHP_VERSION=8.2
            fi
            docker compose up -d --build
            sleep 15

            # --- Permissions & optimizations ---
            sudo mkdir -p storage/framework/{sessions,views,cache}
            sudo chmod -R 775 storage bootstrap/cache
            sudo chown -R \$(whoami):www-data storage bootstrap/cache

            docker compose exec -T app composer install --no-interaction --prefer-dist --no-dev
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan optimize:clear
            docker compose exec -T app php artisan optimize
            docker compose exec -T app php artisan queue:restart
          EOF
