name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite
          coverage: none

      - name: Prepare environment files
        run: |
          cp .env.example .env
          cp .env.example .env.testing
          # Generate random APP_KEY untuk development
          sed -i "s/^APP_KEY=.*/APP_KEY=base64:$(openssl rand -base64 32)/" .env
          # Konfigurasi environment testing
          sed -i 's/^APP_ENV=.*/APP_ENV=testing/' .env.testing
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env.testing
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=:memory:/' .env.testing
          # Generate random APP_KEY untuk testing
          sed -i "s/^APP_KEY=.*/APP_KEY=base64:$(openssl rand -base64 32)/" .env.testing

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Verify environment keys
        run: |
          grep -q 'APP_KEY=base64:' .env || php artisan key:generate --ansi
          grep -q 'APP_KEY=base64:' .env.testing || php artisan key:generate --env=testing --ansi

      - name: Set up storage permissions
        run: |
          mkdir -p storage/framework/{sessions,views,cache}
          chmod -R 775 storage bootstrap/cache

      - name: Run migrations (testing)
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan migrate --force

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            
            cd /var/www/laravel-app

            # Update repository
            git fetch --all
            git reset --hard origin/$(echo ${{ github.ref }} | sed 's|refs/heads/||')

            # Ensure .env exists with proper APP_KEY
            if [ ! -f .env ]; then
              cp .env.example .env
              php artisan key:generate --force
            elif ! grep -q 'APP_KEY=base64:' .env; then
              php artisan key:generate --force
            fi

            # Set permissions
            sudo mkdir -p storage/framework/{sessions,views,cache}
            sudo chmod -R 775 storage bootstrap/cache
            sudo chown -R $USER:www-data storage bootstrap/cache

            # Docker workflow
            docker-compose down || true
            docker-compose build --no-cache
            docker-compose up -d

            # Wait for containers
            sleep 15

            # Run artisan commands in container
            docker-compose exec -T app composer install --no-interaction --prefer-dist --no-dev
            docker-compose exec -T app php artisan config:clear
            docker-compose exec -T app php artisan cache:clear
            docker-compose exec -T app php artisan view:clear
            docker-compose exec -T app php artisan config:cache
            docker-compose exec -T app php artisan route:cache
            docker-compose exec -T app php artisan view:cache
            docker-compose exec -T app php artisan queue:restart
          EOF
